### ISSUE TITLE
Side drawer languages

### ISSUE THREAD

**Issue by longevos** [hugobarragon/react-quizzes#6]
Hi, i have a question, how can i set the default language/s when you edit a question? And by that i mean that i want to change English and Portuguese options like you can see in the image below to Spanish and English. Thanks in advance.

![quizz](https://user-images.githubusercontent.com/82293445/165880981-fc07f345-6889-48b5-bfdb-451671bc7104.PNG)

**Comment by wesvh** [comment]
Encontraste alguna solucion?

**Comment by wesvh** [comment]
Yo encontre una, dentro del modulo, en lib/ToolBox/index.js
Alli se pone la key del idioma y la pregunta de ejemplo, este le asigna a la barra lateral los idiomas por defecto

**Comment by hugobarragon** [comment]
Hello, its all customizable you can read at this section  
https://github.com/hugobarragon/react-quizzes#how-to-add-custom-input  

I made a working example for you with spanish and english  

[![Edit react-quizzesExample-custom-toolbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-quizzesexample-custom-toolbox-70715b?fontsize=14&hidenavigation=1&theme=dark)

![image](https://user-images.githubusercontent.com/35630927/221198462-50b73640-5738-4c74-98a1-ad311da4e1e0.png)
